[workspace]
resolver = "2"
members = [
  "crates/aural-core",
  "crates/aural-audio",
  "crates/aural-engines",
  "crates/aural-models",
  "crates/aural-platform",
  "tools/bench",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
